on:
  push

name: rebuild

jobs:
  rebuild:
    name: "Rebuilding sundries"
    runs-on: ubuntu-latest
    container: bioconductor/orchestratingsinglecellanalysis:latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Update DESCRIPTION and Makefile
        run: |
          rebook::updateDependencies(".", extra=c("Rtsne", "RMTstat", "statmod", "GO.db"))
          rebook::createMakefile()
        shell: Rscript {0}
      - name: Committing to master
        run: | 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add DESCRIPTION Makefile
          git commit -m "Rebuilding sundries." || true
          git push
