---
title: Comments on the book deployment
author: 
- name: Aaron T. L. Lun
date: "`r Sys.Date()`"
vignette: >
  %\VignetteIndexEntry{Comments}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}    
output: 
  BiocStyle::html_document:
    titlecaps: false
    toc: false
---

This package exists only to compile the book on the Bioconductor build system.
It does so by stuffing the book into a package to make it fit into the build system's package-oriented framework,
with some additional tricks to coerce `R CMD build` to actually compile the book chapters.
If you're looking at this vignette, you're probably trying to find something else:

- If you're looking for the compiled book itself, you should go to https://osca.bioconductor.org instead.
The compiled development version of the book is at https://osca-dev.bioconductor.org.
- If you're looking to edit the book, you should go to https://github.com/Bioconductor/OrchestratingSingleCellAnalysis.
This contains the source material from which all compiled versions are derived.
- If you're looking to mimic this set-up for another book, look at https://github.com/LTLA/OrchestratingSingleCellAnalysisBook.
This uses https://github.com/LTLA/TrojanBookBuilder to automatically transplant the book contents into the package.
